---
- name: unzip the dump file
  unarchive:
    src: ftp://ftp.test.com/pub/databases/test/Testdb/latest/user_23_mysql.tar.gz
    dest: /tmp
    remote_src: yes

- mysql_db:
    name: chembl_23
    state: import
    login_host: localhost
    login_user: user
    login_password: devops
    target: /tmp/user_23/user_23_mysql/user_23_mysql.dmp
