---
- name: unzip the dump file
  unarchive:
    src: ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_23_mysql.tar.gz
    dest: /tmp
    remote_src: yes

- mysql_db:
    name: chembl_23
    state: import
    login_host: localhost
    login_user: chembl
    login_password: devops
    target: /tmp/chembl_23/chembl_23_mysql/chembl_23_mysql.dmp
